apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: '2026-02-13T03:50:39Z'
  generation: 1
  labels:
    run: bhaviknginx
  name: bhaviknginx
  namespace: bhavikns
  resourceVersion: '1770954646121071013'
  uid: 87e57a90-e2eb-4e4f-8a72-2d2980437f06
spec:
  containers:
  - image: nginx:1.16
    imagePullPolicy: IfNotPresent
    name: bhaviknginx
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rjv4d
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-bhavikk8cluster-default-pool-9eacd922-cptr
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-rjv4d
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: '2026-02-13T03:50:46Z'
    observedGeneration: 1
    status: 'True'
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: '2026-02-13T03:50:39Z'
    observedGeneration: 1
    status: 'True'
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: '2026-02-13T03:50:46Z'
    observedGeneration: 1
    status: 'True'
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: '2026-02-13T03:50:46Z'
    observedGeneration: 1
    status: 'True'
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: '2026-02-13T03:50:39Z'
    observedGeneration: 1
    status: 'True'
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://f3f17b94b680bfccadece9a56f9b14667ba69f56d21f0b5f4db11521c52eb52a
    image: docker.io/library/nginx:1.16
    imageID: docker.io/library/nginx@sha256:d20aa6d1cae56fd17cd458f4807e0de462caf2336f0b70b5eeb69fcaaf30dd9c
    lastState: {}
    name: bhaviknginx
    ready: true
    resources: {}
    restartCount: 0
    started: true
    state:
      running:
        startedAt: '2026-02-13T03:50:45Z'
    user:
      linux:
        gid: 0
        supplementalGroups:
        - 0
        uid: 0
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-rjv4d
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.128.0.20
  hostIPs:
  - ip: 10.128.0.20
  observedGeneration: 1
  phase: Running
  podIP: 10.24.1.4
  podIPs:
  - ip: 10.24.1.4
  qosClass: BestEffort
  startTime: '2026-02-13T03:50:39Z'